title: Adam Leon Kleppe
logo: IMG_3785 (2).jpg
description: "Hello, my name is Adam Leon Kleppe and I'm an associate professor in mechatronics and robotics at the Department of ICT and Natural Sciences at the Norwegian University for Science and Technology."
theme: jekyll-theme-minimal
