title: Adam Leon Kleppe
logo: https://backends.it.ntnu.no/user-profile-service/rest/files/e82af28d-4bc1-3b78-b804-b7a355e89672
description: "Hello, my name is Adam Leon Kleppe and I'm an associate professor in mechatronics and robotics at the Department of ICT and Natural Sciences at the Norwegian University for Science and Technology."
theme: jekyll-theme-minimal
